### ISSUE TITLE
POST /auth/login

### ISSUE THREAD

**Issue by kzkaneoka** [JejuBrothers/date-night-backend#16]
**Is your request related to a problem? Please describe.**
Registered user needs to login.

**Describe the solution you'd like**
Create `POST /auth/login` with username and password.
Please check [authentication documentation](https://docs.nestjs.com/security/authentication).

**Notes**

- Please create a branch to work on it.
- Please create a PR and assign a reviewer.
- Please format codes with [prettier](https://prettier.io/).

**Comment by Devjacky** [comment]
based on our discussion earlier I've added an additional method to find users by username
