### ISSUE TITLE
Setup Authorization

### ISSUE THREAD

**Issue by kzkaneoka** [JejuBrothers/date-night-backend#26]
**Is your request related to a problem? Please describe.**
Our app needs to authorize users.

**Describe the solution you'd like**
Implement [the role-based access control](https://docs.nestjs.com/security/authorization#basic-rbac-implementation) to control which endpoints are available for which user roles.
Enable JwtAuthGuard [globally](https://docs.nestjs.com/security/authentication#enable-authentication-globally) to control which endpoints are public.
Encrypt & decrypt password.
Encrypt passwords in [src/db/20210515074708_insert_data_into_users.ts](https://github.com/JejuBrothers/date-night-backend/blob/main/src/db/seeds/20210515074708_insert_data_into_users.ts).
Exclude password and user role from response objects.

**Notes**

- Please create a branch to work on it.
- Please create a PR and assign a reviewer.
- Please format codes with [prettier](https://prettier.io/).

**Comment by Devjacky** [comment]
Currently, when a user attempts to log in, auth.service first finds the user in our database (returned from user repo), then compares the passwords to validate the user. 

But when the user repository returns the user object without the user role and password (with $formatJson), authentication fails because there is no password to compare against. How should this be handled?

**Comment by kzkaneoka** [comment]
Good point! However, we don't need to worry about it :)

A user object still contains its user role and password when the auth service receives the object from the user repo. $formatJson excludes them when nest js (with express) returns it with an HTTP response.

Check [model data lifecycle](https://vincit.github.io/objection.js/api/model/overview.html#model-data-lifecycle) for more details.

**Comment by kzkaneoka** [comment]
Hey, please let me know if I should review the pr.
